remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Introduction to the command line interface (Shell)
google_analytics: UA-150953419-1
